apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins-ns
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-jenkins
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: gke-jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 200m
            memory: "200Mi"
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_vol
      volumes:
        - name: jenkins-vol
          emptyDir: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gke-jenkins
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 8080
#   selector:
#     app: gke-jenkins