apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: gke-jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-jenkins
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - name: http-port
          containerPort: 8080
        volumeMounts:
        - name: jenkins-volume
          mountPath: /var/jenkins_volume
        resources: {}
      volumes:
      - name: jenkins-volume
        emptyDir: {}
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gke-jenkins
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 8080
#   selector:
#     app: gke-jenkins