apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: gke-jenkins
---

apiVersion: apps/v1
kind: Deployment
metadata:  
  name: jenkins
  spec:  
  replicas: 1
  selector:
      matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        name: jenkins
        ports:
        - name: http-port
          containerPort: 8080
        volumeMounts:
        - name: jenkins-volume
          mountPath: /var/jenkins_volume
        resources: {}
      volumes:
      - name: jenkins-volume
        emptyDir: {}
status: {}

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gke-jenkins
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 80
#       targetPort: 8080
#   selector:
#     app: gke-jenkins