apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  selector:
    app: jenkins

---
apiVersion: v1
kind: Service
metadata:
  name: lb-jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 30000
      targetPort: 8080
  selector:
    app: jenkins